export enum Genre {
  Action = 'Action',
  Abenteuer = 'Abenteuer',
  Animation = 'Animation',
  Komödie = 'Komödie',
  Krimi = 'Krimi',
  Dokumentarfilm = 'Dokumentarfilm',
  Drama = 'Drama',
  Familie = 'Familie',
  Fantasy = 'Fantasy',
  Historie = 'Historie',
  Horror = 'Horror',
  Musik = 'Musik',
  Mystery = 'Mystery',
  Liebesfilm = 'Liebesfilm',
  ScienceFiction = 'ScienceFiction',
  TVFilm = 'TVFilm',
  Thriller = 'Thriller',
  Kriegsfilm = 'Kriegsfilm',
  Western = 'Western',
}

export const genresObj = {
  Action: 28,
  Abenteuer: 12,
  Animation: 16,
  Komödie: 35,
  Krimi: 80,
  Dokumentarfilm: 99,
  Drama: 18,
  Familie: 10751,
  Fantasy: 14,
  Historie: 36,
  Horror: 27,
  Musik: 10402,
  Mystery: 9648,
  Liebesfilm: 10749,
  ScienceFiction: 878,
  TVFilm: 10770,
  Thriller: 53,
  Kriegsfilm: 10752,
  Western: 37,
};
